import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../UserPanel/Home.module.css'
import Navbar from '../Navbar'
import SideBar from '../SideBar/Index'



export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>User Panel | پنل کاربری </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
        <section className={styles.Flex}>
          <section className={styles.main}>
            <section className={styles.Boxes}>
              <div className={styles.Orders}>
                <div className={styles.forPadding}>
                <i className="fas fa-3x fa-shopping-basket"></i>
                <p className={styles.numbers}>10</p>
              </div>
                <div className={styles.bottomBox}>
                  <p style={{color: '#D9534F'}}>مجموع سفارشات شما</p>
                </div>
              </div>
              <div className={styles.Money}>
              <div className={styles.forPadding}>
                <i className="fas fa-3x fa-coins"></i>
                <p className={styles.numbers}>10</p>
              </div>
                <div className={styles.bottomBox}>
                  <p style={{color: '#F0AD4E'}}>کیف پول</p>
                </div>
              </div>
              <div className={styles.Tickets}>
              <div className={styles.forPadding}>
                <i className="fas fa-3x fa-clipboard-list"></i>
                <p className={styles.numbers}>10</p>
              </div>
                <div className={styles.bottomBox}>
                  <p style={{color: '#337AB7'}}>مشاوره های شما</p>
                </div>
              </div>
              <div className={styles.Active}>
              <div className={styles.forPadding}>
                <i className="fas fa-3x fa-user-shield"></i>
                <p className={styles.numbers}>10</p>
              </div>
                <div className={styles.bottomBox}>
                  <p style={{color: '#5CB85C'}}>نشان شده ها </p>
                </div>
              </div>
            </section>
            <table style={{width: '80%' , margin: '0 auto' , direction: 'rtl'}} className="table">
              <thead>
                <tr>
                  <th scope="col">تاریخ</th>
                  <th scope="col">وضعیت پرداخت</th>
                  <th scope="col">وضعیت سفارش</th>
                  <th scope="col">مبلغ سفارش</th>
                  <th scope="col">عملیات</th>
                </tr>
              </thead>
              <tbody>
                {props.productsList.map(item => 
                  <tr key={item.id} className={styles.Tbody}>
                    <td>{item.created}</td>
                    <td>{item.payment_status}</td>
                   {item.confirmation ? <td style={{color: 'green'}}>تایید شده</td> : <td style={{color: 'red'}}>لغو شده</td>}
                    <td>{item.amount}</td>
                    <td><Link href={`/Orders/${item.order_id}`}>جزئیات</Link></td>
                  </tr>
                  )}
                  
              </tbody>
            </table>
          </section>
          <section className={styles.SideBar}>
            <SideBar />
          </section>
          </section>
    </div>
  )
}

//get data from database
  export const getServerSideProps = async () => {
    const data = await axios.get(`http://45.159.113.83:800/api/v1/user/orders/`, {
      headers:{
        'Authorization': 'Token '+ '96f20d6d2a398fae5c42a67f1ff34241ae7a459c', 
    },
    })
    const response = data.data.results

    return{
      props:{
          productsList: response
      }
    }
  }
