import axios from "axios";
import { useState } from "react";
import Layout from "../../components/Adviser/Layout";
import styles from "../../styles/ProductsDetails.module.css"
import Head from 'next/head'


export default function ProductsDetails({data}){
    
    const [mainPhoto , setMainPhoto] = useState(data.image)
    const imageHandler = (event) =>{
        setMainPhoto(event)
    }

    return(
        <div className={styles.container}>
            <Head>
                <title>جزئیات محصول</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <section className={styles.main}>
                    <section className={styles.details}>
                        <div className={styles.image}>
                            <img className={styles.big_img} src={mainPhoto} alt="photo" />
                            <div className={styles.image_flex}>
                                <img onClick={() => imageHandler(data.image)} src={data.image} alt="photo" />
                                <img onClick={() => imageHandler(data.image2)} src={data.image2} alt="photo1" />
                                <img onClick={() => imageHandler(data.image3)} src={data.image3} alt="photo2" />
                            </div>
                        </div>
                        <div className={styles.descreption}>
                            <h1>{data.name}</h1>
                            <hr />
                            <div className={styles.descreption_text}>
                                <div style={{fontSize: '14px' , textAlign: 'justify'}} className="product-des" dangerouslySetInnerHTML={{ __html: data.descreption }}></div>
                            </div>
                        </div>
                    </section>
                    <section className={styles.add_to_card}>
                        <p> <i className="fas fa-store-alt"></i> فروشنده : {data.manufacturer_company}</p>
                        <hr style={{opacity: '0.5'}} />
                        <p> <i className="fas fa-check"></i> گارانتی اصالت و سلامت فیزیکی کالا</p>
                        <hr style={{opacity: '0.5'}} />
                        <p> <i className="fas fa-warehouse"></i> موجود در انبار </p>
                        <hr style={{opacity: '0.5'}} />
                        <div className={styles.add_to_card_price}>
                            <p> <i className="fas fa-dollar-sign"></i> قیمت محصول : </p>
                            <p>{data.price} هزار تومان</p>
                        </div>
                        <div className={styles.add_to_card_btn}>
                            <button>افزردن به سبد خرید</button>
                        </div>
                    </section>
                </section>
            </Layout>
        </div>
    )
}


export async function getServerSideProps(context){
    const  slug = context.params;
    const data = await axios.get(encodeURI(`http://45.159.113.83:800/api/v1/product/${slug.ProductsDetails}/`))
    const response = data.data
  
    return{
      props:{data: response}
    }
  }
  