import axios from "axios";
import { useState } from "react";
import Layout from "../../components/Adviser/Layout";
import styles from "../../styles/newsDetails.module.css"
import Head from 'next/head'


export default function Details({data}){
    console.log(data);
    return(
        <div className={styles.container}>
            <Head>
                <title>جزئیات محصول</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <section className={styles.main}>
                    <section className={styles.details}>
                        <div className={styles.image}>
                            <img className={styles.big_img} src={data.title_image} alt="photo" />
                        </div>
                        <div className={styles.descreption}>
                            <h1>{data.title}</h1>
                            <hr />
                            <div className={styles.descreption_text}>
                                <div style={{fontSize: '14px' , textAlign: 'justify'}} className="product-des" dangerouslySetInnerHTML={{ __html: data.body }}></div>
                                <p style={{textAlign: 'left' , color: '#999999' , marginTop: '20px' , fontSize: '12px'}}>
                                    {data.created_at} . By {data.author.first_name} {data.author.last_name}
                                </p>
                            </div>
                        </div>
                    </section>
                </section>
            </Layout>
        </div>
    )
}

export async function getServerSideProps(context){
    const  slug = context.params;
    const data = await axios.get(encodeURI(`http://45.159.113.83:800/api/v1/news/${slug.Details}/`))
    const response = data.data
  
    return{
      props:{data: response}
    }
}
  