import { useState } from "react";
import HeroSection from "../components/HeroSection/HeroSection";
// import Slider from "../components/Slider/Slider";
import dynamic from "next/dynamic";
import {  homeObjectFour,  homeObjectOne,  homeObjectThree,  homeObjectTwo,  homeObjectFive,} from "../components/InfoSection/Data";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import SliderOne from "../components/cardslider/sliderone";

const InfoSection = dynamic(() =>
  import("../components/InfoSection/InfoSection"),
);
const Services = dynamic(() => import("../components/Services/Services"));
const Services2 = dynamic(() => import("../components/Services2/Service2"));
const Footer = dynamic(() => import("../components/Footer/Footer"));

function Home({ user }) {
  const [isOpen, setIsOpen] = useState(false);

  const toggle = () => {
    setIsOpen(!isOpen);
  };

  return (
    <div>
      <Head>
        <title>VetNOW</title>
        <meta name="وتنا" content="Generated by Online CEO" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout user={user}>
        <HeroSection />
        {/* <Slider/> */}
                      <div style={{width: "100%", height: "100%" , backgroundColor: '#232f3e',overflow: 'hidden'}}>
                         <SliderOne  style={{width: "100%" , backgroundCo:"#fff"}} 
                        img1='/images/000000.jpg' img2='/images/onlinedr2.jpg' img3='/images/farm300.jpg' img4='/images/tools98.jpg' img5='/images/myna.jpg' img6='/images/vitamin012.jpg'
                        title1=' جوجه گوشتی' title2='دامپزشک آنلاین' title3='آنالیز گله ' title4='تجهیزات پرورشی' title5='منابع آموزشی' title6='ویتامین , مکمل '
                         />
                      </div>  
                      <div style={{width: "100%", height: "100%" , backgroundColor: '#232f3e',overflow: 'hidden'}}>
                         <SliderOne  style={{width: "100%"}} 
                        img1='/images/fram901.png' img2='/images/fram902.png' img3='/images/fram903.png' img4='/images/fram904.png' img5='/images/fram905.png' img6='/images/fram906.png'
                        title1='طوطی ' title2='بوقلمون' title3='نژادهای خاص' title4='عروس هلندی' title5='قوها' title6='طیور بومی'
                         />
                      </div>  
        <Services />
        <Services2 />
        <InfoSection {...homeObjectOne} />
        <InfoSection {...homeObjectTwo} />
        <InfoSection {...homeObjectThree} /> 
                     <div style={{width: "100%", height: "100%" , backgroundColor: '',overflow: 'hidden'}}>
                         <SliderOne  style={{width: "100%"}} 
                        img1='/images/fram924.png' img2='/images/9854.png' img3='/images/fram923.png' img4='/images/fram925.png' img5='/images/fram923.png' img6='/images/9854.png'
                        title1='xxx' title2='xxxx' title3='xxxx' title4='xxxx' title5='xxxxx' title6='xxxx'
                         />
                      </div>  
        <InfoSection {...homeObjectFour} />
       <InfoSection {...homeObjectFive} />
        <Footer />
      </Layout>
    </div>
  );
}



export default Home;
